language: c 

sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$HOME/miniconda/envs/ci/bin/:$PATH
    - common_py_deps="ipython-notebook"

before_install:
- tools/ci/travis/install_miniconda.sh
- conda install -qy $common_py_deps
- conda list
# use a headless plotting backend for matplotlib
- mkdir -p ~/.config/matplotlib/
- touch ~/.config/matplotlib/matplotlibrc
- "echo 'backend: Agg' >> ~/.config/matplotlib/matplotlibrc"
- conda config --add channels omnia 

install:
- conda install -qy pyemma-dev

script:
- test/run_ipython_tests.sh  
